entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8081"

providers:
  file:
    filename: /etc/traefik/dynamic.yml

certificatesResolvers:
  myresolver:
    acme:
      email: "${LETS_ENCRYPT_EMAIL}"
      storage: /etc/traefik/acme.json
      keyType: RSA4096
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  insecure: true

log:
  level: ${TRAEFIK_LOG_LEVEL}
